//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnyesensmarter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int UserID { get; set; }
        public int QuestionID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<System.DateTime> LastTook { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
